---
- name: "FQCN migration process (1)"
  hosts: localhost
  gather_facts: no
  vars:
    upstream_name: keycloak_quarkus
    downstream_name: rhbk
    upstream_collection_name: keycloak
    downstream_namespace: redhat
    upstream_namespace: middleware_automation
    downstream_projects_dir: ./intermediate
    downstream_project: "{{ lookup('env', 'PWD') }}/intermediate/rhbk"
    project_root_folder: "{{ lookup('env', 'PWD') }}/upstream/keycloak.git"
    excluded_roles_from_downstream:
      - roles/keycloak
    project_git_url: "{{ lookup('env', 'GIT_REPOSITORY_URL') | default('https://github.com/ansible-middleware/keycloak.git', true) }}"
    project_git_version: "{{ lookup('env', 'GIT_REPOSITORY_BRANCH') | default('main', true) }}"
    gitdescribe_galaxy_version: "{{ true if lookup('env', 'RELEASE_NAME') == '' else false }}"
    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
    post_processors_replacements: []
    galaxy:
      documentation: https://access.redhat.com/documentation/en-us/red_hat_build_of_keycloak/
      homepage: https://access.redhat.com/products/red-hat-build-of-keycloak/
    # anything inside <!--start {{ <downstream_placeholder>_delete }} --> and <!--end {{ <downstream_placeholder>_delete }} --> will be removed
    downstream_placeholder_delete:
      - build_status
    # anything inside <!--start {{ <downstream_placeholder>_content }} --> and <!--end {{ <downstream_placeholder>_content }} --> will be replaced with content
    downstream_placeholder_content: []
  pre_tasks:
    - name: "Git clone {{ project_git_url }} into {{ lookup('env', 'PWD') }}/upstream/keycloak.git"
      ansible.builtin.include_role:
        name: community.fqcn_migration.git
        tasks_from: clone.yml

  tasks:
    - ansible.builtin.include_role:
        name: community.fqcn_migration.fqcn_migration
      tags: always

- name: "FQCN migration process (2)"
  hosts: localhost
  gather_facts: no
  vars:
    upstream_name: keycloak
    downstream_name: rhbk
    downstream_namespace: redhat
    upstream_namespace: redhat
    downstream_projects_dir: ./downstream
    downstream_project: "{{ lookup('env', 'PWD') }}/downstream/rhbk"
    project_root_folder: "{{ lookup('env', 'PWD') }}/intermediate/rhbk"
    upstream_projects_dir: "{{ workdir }}/intermediate"
    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
    post_processors_replacements:
      - match: "rhbk[.]service[.]j2"
        replace: "keycloak.service.j2"
        file: 'systemd[.]yml$'
      - match: "rhbk-sysconfig[.]j2"
        replace: "keycloak-sysconfig.j2"
        file: 'systemd[.]yml$'
      - match: "- rhbk[.]conf"
        replace: "- keycloak.conf"
        file: 'main[.]yml$'
      - match: "rhbk[.]fact"
        replace: "keycloak.fact"
      - match: "ansible_local[.]rhbk"
        replace: "ansible_local.keycloak"
      - match: "org[.]rhbk[.]"
        replace: "org.keycloak."
      - match: "rhbk[.]org"
        replace: "keycloak.org"
      - match: "spid-rhbk-provider"
        replace: "spid-keycloak-provider"
        file: "converge.yml$"
      - match: "org.rhbk"
        replace: "org.keycloak"
        file: "converge.yml$"
      - match: "rhbk-kerberos-federation"
        replace: "keycloak-kerberos-federation"
        file: "converge.yml$"
      - match: "red-hat-build-of-rhbk"
        replace: "red-hat-build-of-keycloak"
        file: "README.md$"
      - match: "[/]github.com[/]ansible-middleware[/]rhbk"
        replace: "/github.com/ansible-middleware/keycloak"
        file: "CHANGELOG.md$"
    galaxy:
      documentation: https://access.redhat.com/documentation/en-us/red_hat_build_of_keycloak/
      homepage: https://access.redhat.com/products/red-hat-build-of-keycloak/
    # anything inside <!--start {{ <downstream_placeholder>_content }} --> and <!--end {{ <downstream_placeholder>_content }} --> will be replaced with content
    downstream_placeholder_content:
      - placeholder: galaxy_download
        content: |
          ### Installing the Collection from Automation Hub

          Before using the collection, you need to setup Ansible Automation Hub as galaxy server; then install it via the CLI:

              ansible-galaxy collection install redhat.rhbk
      - placeholder: roles_paths
        content: |
          ### Included roles

          * [`rhbk`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/rhbk/content/role/rhbk/): role for installing the service.
          * [`rhbk_realm`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/rhbk/content/role/rhbk_realm/): role for configuring a realm, user federation(s), clients and users, in an installed service.
      - placeholder: support
        content: |
          ## Support

          redhat.rhbk collection v{{ galaxy_version | default('0.0.0-dev') }} is for [Technical Preview](https://access.redhat.com/support/offerings/techpreview).
          If you have any issues or questions related to collection, please don't hesitate to contact us on <Ansible-middleware-core@redhat.com> or open an issue on
          <https://github.com/ansible-middleware/keycloak/issues> referring to the keycloak_quarkus role
      - placeholder: rhn_credentials
        content: |
          #### Downloading from the Customer Portal

          The `rhbk` role supports downloading and installing from the Red Hat Customer Portal using credentials associated to a service account. After having
          authenticated in the customer portal, navigate to the hybrid cloud console, and select the [services account tab](https://console.redhat.com/application-services/service-accounts)
          to create one, if needed. Client ID and Client Secret associated to the service account need to be provided to the collection using the following variables:
          ```
          rhn_username{{':'}} '<client_id>'
          rhn_password{{':'}} '<client_secret>'
          ```

          The downloaded product archive will be stored in the controller working directory, and then distributed to target nodes.
      - placeholder: rhbk_playbook
        content: |
          * The below example playbook can install based on the defined variables (using most defaults).

          ```
          ---
          - name: Playbook for rhbk Hosts
            hosts: all
            vars:
              rhbk_admin_password: "remembertochangeme"
            roles:
              - redhat.rhbk.rhbk
          ```

          Both playbooks include the `rhbk` role, with different settings, as described in the following sections.

          For full service configuration details, refer to the [rhbk role README](/ansible/automation-hub/repo/published/redhat/rhbk/content/role/rhbk/).
      - placeholder: rhbk_realm_playbook
        content: |
          The below example playbook can creates or updates provided realm, user federation(s), client(s), client role(s) and client user(s).

          ```
          ---
          - name: Playbook for rhbk Hosts
            hosts: all
            vars:
              rhbk_admin_password: "remembertochangeme"
              rhbk_clients:
                - name: TestClient1
                  client_id: TestClient1
                  roles:
                    - TestClient1Admin
                    - TestClient1User
                  realm: TestRealm
                  public_client: true
                  web_origins:
                    - http://testclient1origin/application
                    - http://testclient1origin/other
                  users:
                    - username: TestUser
                      password: password
                      client_roles:
                        - client: TestClient1
                          role: TestClient1User
                          realm: TestRealm
            roles:
              - role: redhat.rhbk.rhbk_realm
                rhbk_realm: TestRealm
          ```
      - placeholder: rhbk_realm_readme
        content: |
          For full configuration details, refer to the [rhbk_realm role](/ansible/automation-hub/repo/published/redhat/rhbk/content/role/rhbk_realm/).
      - placeholder: license
        content: |
          See [LICENSE](https://github.com/ansible-middleware/keycloak/blob/main/LICENSE) to view the full text.
      - placeholder: description
        content: |
          Collection to install and configure [Red Hat Build of Keycloak](https://access.redhat.com/products/red-hat-build-of-keycloak).
      - placeholder: description_realm
        content: |
          Create realms and clients in [Red Hat Build of Keycloak](https://access.redhat.com/products/red-hat-build-of-keycloak).
  tasks:
    - ansible.builtin.include_role:
        name: community.fqcn_migration.fqcn_migration
      tags: always

  post_tasks:
    - name: "Perform release (if requested): {{ release_version == '' | ternary('no release version provided', release_version) }}."
      ansible.builtin.include_role:
        name: fqcn_migration
        tasks_from: release.yml
      when:
        - release_version is defined and release_version != ""

    - name: "Build collection for {{ downstream_name }}"
      ansible.builtin.command: ansible-galaxy collection build .
      args:
        chdir: "{{ downstream_project }}"
