---
- ansible.builtin.import_playbook: community.fqcn_migration.fqcn_migration
  vars:
    upstream_name: keycloak
    downstream_name: sso
    downstream_namespace: 'redhat'
    upstream_namespace: 'middleware_automation'
    project_git_url: "https://github.com/ansible-middleware/{{ upstream_name }}.git"
    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
      - { upstream_name: 'middleware_automation.wildfly', downstream_name: 'redhat.eap' }
    post_processors_replacements:
      - match: "sso[.]service[.]j2"
        replace: "keycloak.service.j2"
        file: 'systemd[.]yml$'
      - match: "sso-sysconfig[.]j2"
        replace: "keycloak-sysconfig.j2"
        file: 'systemd[.]yml$'
      - match: "sso-service[.]sh[.]j2"
        replace: "keycloak-service.sh.j2"
        file: 'systemd[.]yml$'
      - match: 'cache-container name="sso"( modules="org[.]sso[.]sso-model-infinispan")?'
        replace: 'cache-container name="keycloak" modules="org.keycloak.keycloak-model-infinispan"'
        file: 'xml.j2$'
      - match: "org[.]sso[.]"
        replace: "org.keycloak."
      - match: "sso[.]org"
        replace: "keycloak.org"
      - match: "sso-server-subsystem"
        replace: "keycloak-server-subsystem"
        file: 'xml.j2$'
      - match: "[$][{]sso[.]"
        replace: "${keycloak."
      - match: "urn:jboss:domain:sso-server:1[.]1"
        replace: "urn:jboss:domain:keycloak-server:1.1"
        file: 'xml.j2$'
      - match: "start_sso[.]yml"
        replace: "start_keycloak.yml"
        file: '[.]yml$'
      - match: "stop_sso[.]yml"
        replace: "stop_keycloak.yml"
        file: '[.]yml$'
      - match: "java:jboss/infinispan/container/sso"
        replace: "java:jboss/infinispan/container/keycloak"
        file: 'xml.j2$'
      - match: 'local-cache name="sso"'
        replace: 'local-cache name="keycloak"'
        file: 'xml.j2$'
      - match: 'sso-database-update[.]sql'
        replace: 'keycloak-database-update.sql'
        file: 'xml.j2$'
      - match: '/bin/add-user-sso'
        replace: '/bin/add-user-keycloak'
        file: 'main[.]yml$'
    galaxy:
      documentation: https://access.redhat.com/documentation/en-us/red_hat_single_sign-on
      homepage: https://access.redhat.com/products/red-hat-single-sign-on
    # anything inside <!--start {{ <downstream_placeholder>_delete }} --> and <!--end {{ <downstream_placeholder>_delete }} --> will be removed
    downstream_placeholder_delete:
      - build_status
      - roles_paths
    # anything inside <!--start {{ <downstream_placeholder>_content }} --> and <!--end {{ <downstream_placeholder>_content }} --> will be replaced with content
    downstream_placeholder_content:
      - placeholder: roles_paths
        content: |
          ### Included roles

          * [`keycloak`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/sso/content/role/sso/): role for installing the service.
          * [`keycloak_realm`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/sso/content/role/sso_realm/): role for configuring a realm, user federation(s), clients and users, in an installed service.
          * [`keycloak_quarkus`](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/sso/content/role/sso_quarkus/): role for installing the quarkus variant of keycloak (>= 17.0.0).
      - placeholder: ansible_version
        content: |
          Red Hat has tested this collection against Ansible versions 2.13.0 or later.

          Red Hat might test the plug-ins and modules that are within a collection with specific Ansible versions only. A collection can contain metadata that identifies these Ansible versions.
      - placeholder: galaxy_download
        content: |
          ### Installing the Collection from Automation Hub

          Before using the collection, you need to setup Ansible Automation Hub as galaxy server; then install it via the CLI:

              ansible-galaxy collection install redhat.sso
      - placeholder: support
        content: |
          ## Support

          redhat.sso collection v{{ galaxy_version | default('0.0.0-dev') }} is for [Technical Preview](https://access.redhat.com/support/offerings/techpreview).
          If you have any issues or questions related to collection, please don't hesitate to contact us on <Ansible-middleware-core@redhat.com> or open an issue on
          <https://github.com/ansible-middleware/keycloak/issues>
      - placeholder: rhn_credentials
        content: |
          ## Downloading from the Customer Portal

          The `redhat.sso.sso` role supports downloading and installing from the Red Hat Customer Portal using credentials associated to a service account. After
          login in the customer portal and navigating to the hybrid cloud console, select the [services account tab](https://console.redhat.com/application-services/service-accounts)
          to create one, if needed. Client ID and Client secret associated to the service account needs to be provided with the following variables are defined:
          ```
          rhn_username{{':'}} '<client_id>'
          rhn_password{{':'}} '<client_secret>'
          ```

          The downloaded product archive will be stored in the controller working directory, and then distributed to target nodes.

          When patching is requested, via the `sso_apply_patches` variable, the most recently published cumulative patch will be installed; to use a specific patch version instead,
          set it with the `sso_patch_version` variable.

          NOTE: downgrading patches is not supported.
